language: node_js
node_js:
- "0.12"

machine:
  services:
    - docker

dependencies:
  override:
    - sudo pip install --upgrade docker-compose==1.3.3

deployment:
  hub:
    branch: master
    commands:
      - $DEPLOY

sudo: false

before_script:
- mysql -hlocalhost -P3306 -e 'create database develop;'
- echo "USE mysql;\nUPDATE user SET password=PASSWORD('root') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root

script:
- npm install sails@0.12.1
- npm install oplakus/appdev-cli
- appdev install sails --develop --travisCI
