appdev-cli:
  build: ./app
  volumes:
    - "./app:/src/app"
  ports:
    - "80:3000"
  links:
   - mysqlsails
mysqlsails:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
        - "3306:3306"

