appdev-cli:
  build: ./app
  volumes:
    - "./app:/src/app"
  ports:
    - "80:3000"
  links:
   - mysql
mysql:
    image: mysql:latest
    ports:
        - "3306:3306"
deployment:
  hub:
    branch: master
    commands:
      - $DEPLOY

